"""Prompt templates for the requirement-review workflow."""

from .templates.registry import (
    CLARIFY_PARSER_REVIEW_PROMPT,
    PARSER_REVIEW_PROMPT,
    PLANNER_REVIEW_PROMPT,
    REVIEWER_REVIEW_PROMPT,
    RISK_REVIEW_PROMPT,
)

PARSER_SYSTEM_PROMPT = PARSER_REVIEW_PROMPT.system_prompt
PARSER_USER_PROMPT = PARSER_REVIEW_PROMPT.user_prompt

CLARIFY_PARSER_SYSTEM_PROMPT = CLARIFY_PARSER_REVIEW_PROMPT.system_prompt
CLARIFY_PARSER_USER_PROMPT = CLARIFY_PARSER_REVIEW_PROMPT.user_prompt

REVIEWER_SYSTEM_PROMPT = REVIEWER_REVIEW_PROMPT.system_prompt
REVIEWER_USER_PROMPT = REVIEWER_REVIEW_PROMPT.user_prompt

PLANNER_SYSTEM_PROMPT = PLANNER_REVIEW_PROMPT.system_prompt
PLANNER_USER_PROMPT = PLANNER_REVIEW_PROMPT.user_prompt

RISK_SYSTEM_PROMPT = RISK_REVIEW_PROMPT.system_prompt
RISK_USER_PROMPT = RISK_REVIEW_PROMPT.user_prompt
