"""Prompt templates for delivery planning skills."""

from .templates.registry import (
    CLAUDE_CODE_PROMPT_GENERATION_REVIEW_PROMPT,
    CODEX_PROMPT_GENERATION_REVIEW_PROMPT,
    IMPLEMENTATION_PLAN_REVIEW_PROMPT,
    TEST_PLAN_REVIEW_PROMPT,
)

IMPLEMENTATION_PLAN_SYSTEM_PROMPT = IMPLEMENTATION_PLAN_REVIEW_PROMPT.system_prompt
IMPLEMENTATION_PLAN_USER_PROMPT = IMPLEMENTATION_PLAN_REVIEW_PROMPT.user_prompt

TEST_PLAN_SYSTEM_PROMPT = TEST_PLAN_REVIEW_PROMPT.system_prompt
TEST_PLAN_USER_PROMPT = TEST_PLAN_REVIEW_PROMPT.user_prompt

CODEX_PROMPT_SYSTEM_PROMPT = CODEX_PROMPT_GENERATION_REVIEW_PROMPT.system_prompt
CODEX_PROMPT_USER_PROMPT = CODEX_PROMPT_GENERATION_REVIEW_PROMPT.user_prompt

CLAUDE_CODE_PROMPT_SYSTEM_PROMPT = CLAUDE_CODE_PROMPT_GENERATION_REVIEW_PROMPT.system_prompt
CLAUDE_CODE_PROMPT_USER_PROMPT = CLAUDE_CODE_PROMPT_GENERATION_REVIEW_PROMPT.user_prompt
