"""Template registry accessors."""

from .models import (
    BASE_SECTION_ORDER,
    AdapterPromptTemplate,
    DeliveryArtifactTemplate,
    ReviewPromptTemplate,
    TemplateDefinition,
)
from .registry import (
    TemplateNotFoundError,
    TemplateRegistryError,
    TemplateTypeNotFoundError,
    TemplateVersionNotFoundError,
    find_templates_by_version,
    get_adapter_prompt_template,
    get_default_template,
    get_delivery_artifact_template,
    get_review_prompt_template,
    get_template,
    get_template_by_version,
    get_template_record,
    get_templates_by_type,
    is_default_template,
    list_template_records,
    list_templates,
    register_template,
    resolve_default_template_version,
    resolve_template_version,
)

__all__ = [
    "BASE_SECTION_ORDER",
    "AdapterPromptTemplate",
    "DeliveryArtifactTemplate",
    "ReviewPromptTemplate",
    "TemplateDefinition",
    "TemplateNotFoundError",
    "TemplateRegistryError",
    "TemplateTypeNotFoundError",
    "TemplateVersionNotFoundError",
    "find_templates_by_version",
    "get_adapter_prompt_template",
    "get_default_template",
    "get_delivery_artifact_template",
    "get_review_prompt_template",
    "get_template",
    "get_template_by_version",
    "get_template_record",
    "get_templates_by_type",
    "is_default_template",
    "list_template_records",
    "list_templates",
    "register_template",
    "resolve_default_template_version",
    "resolve_template_version",
]
